Update spatiotemporal chapter
mlr-org/mlr3book pull request #372
Opened 2022-06-15 19:05 UTC by pat-s

To reflect {mlr3spatiotempcv} 2.0 changes.

@be-marc Review appreciated!

We also need to add more content about {mlr3spatial}. I've also now split the content into

- perf. estimation with nested CV ({mlr3spatiotempcv})
- spatial prediction ({mlr3spatial})

{mlr3spatiotempcv} still needed as there were some issues with the return of the cstf autoplot() fun.

2022-06-26 20:32 UTC, pat-s commented
@be-marc I'd like to merge this very soon to have a working documentation for the current {mlr3spatiotempcv} release. Review still welcome, we can do a follow-up PR if needed :)

2022-06-28 10:24 UTC, be-marc requested changes

2022-06-28 10:24 UTC, be-marc commented on book/08-special-spatiotemp.qmd
>  In practice however, one needs to create a spatiotemporal task via `r ref("TaskClassifST")`/`r ref("TaskRegrST")` and set the `crs` argument.
or is extracted from the sf object.

2022-06-28 10:24 UTC, be-marc commented on book/08-special-spatiotemp.qmd
> +The use of `range = 1000L` is arbitrary here and should not be c/p into a real application.
c/p -> copy-pasted

2022-06-30 12:21 UTC, pat-s commented on book/08-special-spatiotemp.qmd
> +Here, the performance of the classification tree learner is around 0.05 percentage points worse when using Spatial Cross-Validation (SpCV) compared to Non-Spatial Cross-Validation (NSpCV).
Good catch!

2022-06-30 12:28 UTC, pat-s commented on book/08-special-spatiotemp.qmd
> +1. Use the constructor of the `r ref("Task")` directly via `$new()`
Ok I've removed the contructor option.

2022-06-30 12:28 UTC, pat-s commented
@be-marc Please approve and squash merge if ok 👍

2022-07-06 08:30 UTC, pat-s commented
Merging since you are on holiday.

2022-07-06 08:31 UTC, merged