Special v3
mlr-org/mlr3book pull request #562
Opened 2023-03-30 09:52 UTC by RaphaelS1

@larskotthoff I've addressed all comments from https://github.com/mlr-org/mlr3book/issues/561 in https://github.com/mlr-org/mlr3book/pull/562/commits/4254916064493d31ed9692f4b3e55a5fec84a4dc (Note ignored comments about Prob Regr for now subject to conversation in MM)

@pat-s I've addressed all comments from https://github.com/mlr-org/mlr3book/pull/560 in https://github.com/mlr-org/mlr3book/pull/562/commits/3f7d405ef43c28033986b1f48d5cda07aeefc90a

Re-reviews appreciated

2023-03-30 14:46 UTC, larskotthoff approved these changes

2023-03-30 14:47 UTC, larskotthoff commented
Thanks, looks good. I'll have a look at the entire chapter again once this has been merged.

2023-04-06 11:28 UTC, pat-s requested changes
Thanks for the implementation of changes! Definitely an improvement over the previous one and well appreciated. Even though I struggled a bit understanding the changes made and the thoughts behind as these were not shared alongside the changes :) I didn't recheck all my previous comments again but I am almost happy with the current state (see below) 🙂:

Additional improvement suggestions which are not in the diff:

> In the example below we load the leipzig_points file for training

-> "In the example below we load the leipzig_points points dataset for training"

> Both files are shipped with, and can be downloaded from, [mlr3spatial](https://mlr3spatial.mlr-org.com/).

-> Both datasets are included as examples data within [mlr3spatial](https://mlr3spatial.mlr-org.com/).

## Spatial prediction

Here we're currently still missing mentioning the actual motivation for the existence of {mlr3spatial}, i.e. what it does to make the lifer easier for users:

"This seemed easy, right? Under the hood, mlr3spatial takes away a lot of cumbersome handling and coercing between R objects and formats - including taking care to not loose the spatial reference of the data.
If you would attempt this from scratch yourself, you would need to coerce between spatial objects and plain data.tables a lot. Not even mentioning handling the prediction step in a way that your memory is not overflowing but still allowing you to use more than one care of your machine.
All of this is handled by mlr3spatial to make the modeler's life easier. Depending on the data and your machine, it might also outperform the native parallelization methods of the spatial packages as shown [in this benchmark conducted by us](https://mlr3spatial.mlr-org.com/articles/benchmark.html).

*Feel free to rephrase above as needed. I guess Marc could also have a look at this as he implemented most of the logic in mlr3spatial.*

2023-04-06 11:28 UTC, pat-s commented on book/special.qmd
> +Instead we provide new resampling methods in `r mlr3spatiotempcv` to account for the similarity in the train and test sets during resampling that originates from spatial autocorrelation.
```suggestion
Instead we provide additional resampling methods in `r mlr3spatiotempcv` to account for the similarity in the train and test sets during resampling that originates from spatiotemporal autocorrelation.
```

The methods are not new, i.e. all of them existed before and we just "use" them. There is no method that has been newly developed in tempcv.

I think adding a disclaimer here regarding the use of the words "spatial autocor." or "spatiotemporal autocor." would be good. I would prefer to use/introduce the acronym STAC (spatiotemporal autocorrelation) and state that it depends on the data and context whether the autocorrelation is spatial, temporal or spatiotemporal.
This way one does not always have to switch between the different terms in each section and it is clear that the focus is on accounting for a combination of all, if existent.

EDIT: I see there is a disclaimer/note coming further down the text. I'd move it up so readers see it earlier and get clarification on the use of the words and different types of autocor.

2023-04-06 11:28 UTC, pat-s commented on book/special.qmd
> +Below we benchmark a decision tree on the `r ref("mlr_tasks_ecuador")` task using two different repeated cross-validation resampling methods, the first ("NSpCV" (non-spatial cross-validation)) is a s
```suggestion
Below we benchmark a decision tree on the `r ref("mlr_tasks_ecuador")` task using two different repeated cross-validation resampling methods, the first ("NSpCV" (non-spatial cross-validation)) is a non-spatial resampling method from `r mlr3`, the second ("SpCV" (spatial cross-validation)) is from `r mlr3spatiotempcv` and is optimized for spatial data.
```

2023-04-06 11:28 UTC, pat-s commented on book/special.qmd
> +Now we have seen why spatial resampling matter we can take a look at what is implemented in `r mlr3spatiotempcv`.
```suggestion
Now we have seen why spatial resampling matters we can take a look at what methods are available in `r mlr3spatiotempcv`.
```

2023-04-06 11:28 UTC, pat-s commented on book/special.qmd
>  Finally, with `r mlr3spatial` and `mlr3spatiotempcv`, it is possible to perform spatial analysis to make predictions using co-ordinates as features and to make spatial predictions.
```suggestion
Finally, with `r mlr3spatial` and `r mlr3spatiotempcv`, it is possible to perform spatial analysis to make predictions using co-ordinates as features and to make spatial predictions.
```

2023-04-06 12:33 UTC, merged